# Generated by Django 3.2.15 on 2022-10-21 00:44

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_size', models.IntegerField(null=True)),
                ('generations', models.IntegerField()),
                ('pop_bottleneck', models.IntegerField(null=True)),
                ('generation_bottleneck', models.IntegerField(null=True)),
                ('p_inicial', models.DecimalField(decimal_places=10, max_digits=11)),
                ('WAA', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('WAa', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('Waa', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('s', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('h', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('u', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('parametros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parametros')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resultados')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grupo')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.simulacao')),
            ],
        ),
    ]
