# Generated by Django 3.2.15 on 2022-10-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupo_gruposimulacao_parametros_resultados_simulacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametros',
            name='generations',
            field=models.IntegerField(null=True),
        ),
    ]
