# Generated by Django 3.2.15 on 2022-11-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_simulacao_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametros',
            old_name='p_inicial',
            new_name='initial_p',
        ),
        migrations.RenameField(
            model_name='parametros',
            old_name='pop_size',
            new_name='population_size',
        ),
        migrations.AddField(
            model_name='parametros',
            name='populations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='parametros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parametros'),
        ),
    ]
